$src = "c:\Users\Κωνσταντίνος Καμπάνη\Desktop\Index\Ενέργεια"
$dst = "c:\Users\Κωνσταντίνος Καμπάνη\Desktop\Index\portal\public\files"

function cp($from, $to) {
    $dir = Split-Path $to -Parent
    if (!(Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
    Copy-Item $from $to -Force
    Write-Host "OK: $to"
}

# ===== ΖΕΝΙΘ =====
cp "$src\Ζενίθ\Ρεύμα\ΝΕΑ ΕΠΕΞΕΡΓΑΣΙΜΗ ΑΙΤΗΣΗ ΡΕΥΜΑ ΑΕΡΙΟ ΚΑΙ ΠΑΓΙΑ 3_2026.pdf" "$dst\zenith\revma\NEA EPEXERGASIMH AITHSH REUMA AERIO KAI PAGIA 3_2026.pdf"
cp "$src\Ζενίθ\Ρεύμα\Γενικοί όροι ρεύμα.pdf" "$dst\zenith\revma\Genikoi oroi reuma.pdf"
cp "$src\Ζενίθ\Ρεύμα\Οικιακά\Κίτρινα\Power Home Confort.pdf" "$dst\zenith\revma\oikiaka\kitrina\Power Home Confort.pdf"
cp "$src\Ζενίθ\Ρεύμα\Οικιακά\Κίτρινα\Power Home Save.pdf" "$dst\zenith\revma\oikiaka\kitrina\Power Home Save.pdf"
cp "$src\Ζενίθ\Ρεύμα\Οικιακά\Κίτρινα\Power Home Select.pdf" "$dst\zenith\revma\oikiaka\kitrina\Power Home Select.pdf"
cp "$src\Ζενίθ\Ρεύμα\Οικιακά\Κίτρινα\Power Home Student.pdf" "$dst\zenith\revma\oikiaka\kitrina\Power Home Student.pdf"
cp "$src\Ζενίθ\Ρεύμα\Οικιακά\Μπλέ\Power Home Control PLus.pdf" "$dst\zenith\revma\oikiaka\mple\Power Home Control PLus.pdf"
cp "$src\Ζενίθ\Ρεύμα\Οικιακά\Μπλέ\Power Home Control Plus Boost Promo.pdf" "$dst\zenith\revma\oikiaka\mple\Power Home Control Plus Boost Promo.pdf"
cp "$src\Ζενίθ\Ρεύμα\Οικιακά\Μπλέ\Power Home Control Plus Promo.pdf" "$dst\zenith\revma\oikiaka\mple\Power Home Control Plus Promo.pdf"
cp "$src\Ζενίθ\Ρεύμα\Οικιακά\Μπλέ\Power Home Simple fx.pdf" "$dst\zenith\revma\oikiaka\mple\Power Home Simple fx.pdf"
cp "$src\Ζενίθ\Ρεύμα\Επαγγελματικά\Κίτρινα\Power Business Basic 2.0.pdf" "$dst\zenith\revma\epaggelmatika\kitrina\Power Business Basic 2.0.pdf"
cp "$src\Ζενίθ\Ρεύμα\Επαγγελματικά\Κίτρινα\Power Business Basic.pdf" "$dst\zenith\revma\epaggelmatika\kitrina\Power Business Basic.pdf"
cp "$src\Ζενίθ\Ρεύμα\Επαγγελματικά\Μπλε\Power Business Trust 4.0.pdf" "$dst\zenith\revma\epaggelmatika\mple\Power Business Trust 4.0.pdf"
cp "$src\Ζενίθ\Ρεύμα\Επαγγελματικά\Πράσινα\Power Business Start.pdf" "$dst\zenith\revma\epaggelmatika\prasina\Power Business Start.pdf"
cp "$src\Ζενίθ\Αέριο\Αίτηση Φ.Α..pdf" "$dst\zenith\aerio\Aitisi FA.pdf"
cp "$src\Ζενίθ\Αέριο\Γενικοί Όροι Φ.Α..pdf" "$dst\zenith\aerio\Genikoi Oroi FA.pdf"
cp "$src\Ζενίθ\Αέριο\Οικιακό\st_gas_home_save_120e (1).pdf" "$dst\zenith\aerio\oikiako\st_gas_home_save_120e.pdf"
cp "$src\Ζενίθ\Αέριο\Οικιακό\Κυμαινόμενο\Gas Home Now.pdf" "$dst\zenith\aerio\oikiako\kymainom\Gas Home Now.pdf"
cp "$src\Ζενίθ\Αέριο\Οικιακό\Κυμαινόμενο\Gas Home Save Promo 120€.pdf" "$dst\zenith\aerio\oikiako\kymainom\Gas Home Save Promo 120.pdf"
cp "$src\Ζενίθ\Αέριο\Οικιακό\Κυμαινόμενο\Gas Home Save.pdf" "$dst\zenith\aerio\oikiako\kymainom\Gas Home Save.pdf"
cp "$src\Ζενίθ\Αέριο\Οικιακό\Σταθερό\Gas Home Secure.pdf" "$dst\zenith\aerio\oikiako\stathero\Gas Home Secure.pdf"
cp "$src\Ζενίθ\Αέριο\Επαγγελματικό\st_gas_business_save_60e_7 (1).pdf" "$dst\zenith\aerio\epaggelmatiko\st_gas_business_save_60e_7.pdf"
cp "$src\Ζενίθ\Αέριο\Επαγγελματικό\Κυμμενομενο\Gas Business Easy 1.pdf" "$dst\zenith\aerio\epaggelmatiko\kymainom\Gas Business Easy 1.pdf"
cp "$src\Ζενίθ\Αέριο\Επαγγελματικό\Κυμμενομενο\Gas Business Easy 2.pdf" "$dst\zenith\aerio\epaggelmatiko\kymainom\Gas Business Easy 2.pdf"
cp "$src\Ζενίθ\Αέριο\Επαγγελματικό\Κυμμενομενο\Gas Business Save +.pdf" "$dst\zenith\aerio\epaggelmatiko\kymainom\Gas Business Save plus.pdf"
cp "$src\Ζενίθ\Αέριο\Επαγγελματικό\Κυμμενομενο\Gas Business Save Promo 90€.pdf" "$dst\zenith\aerio\epaggelmatiko\kymainom\Gas Business Save Promo 90.pdf"
cp "$src\Ζενίθ\Αέριο\Επαγγελματικό\Κυμμενομενο\Gas Business Save.pdf" "$dst\zenith\aerio\epaggelmatiko\kymainom\Gas Business Save.pdf"
cp "$src\Ζενίθ\Αέριο\Κεντρική Θέρμανση\Gas Central Easy.pdf" "$dst\zenith\aerio\kentriki-thermanssi\Gas Central Easy.pdf"
cp "$src\Ζενίθ\Αέριο\Κεντρική Θέρμανση\Gas Central Save.pdf" "$dst\zenith\aerio\kentriki-thermanssi\Gas Central Save.pdf"

# ===== ΗΡΩΝ =====
cp "$src\Ήρων\Αέριο\Gas Max Share.pdf" "$dst\iron\aerio\Gas Max Share.pdf"
cp "$src\Ήρων\Αέριο\Οικιακό\Gas Max Home 2.pdf" "$dst\iron\aerio\oikiako\Gas Max Home 2.pdf"
cp "$src\Ήρων\Αέριο\Οικιακό\Gas Pass.pdf" "$dst\iron\aerio\oikiako\Gas Pass.pdf"
cp "$src\Ήρων\Αέριο\Οικιακό\Σταθερό\Gas Blue.pdf" "$dst\iron\aerio\oikiako\stathero\Gas Blue.pdf"
cp "$src\Ήρων\Αέριο\Επαγγελματικό\Gas Max Business.pdf" "$dst\iron\aerio\epaggelmatiko\Gas Max Business.pdf"
cp "$src\Ήρων\Ρεύμα\Οικιακά\Κίτρινα\GENEROUS SOLAR  HOME 1.pdf" "$dst\iron\revma\oikiaka\kitrina\GENEROUS SOLAR HOME 1.pdf"
cp "$src\Ήρων\Ρεύμα\Οικιακά\Κίτρινα\HAPPY HOUR FOR ALL HOME.pdf" "$dst\iron\revma\oikiaka\kitrina\HAPPY HOUR FOR ALL HOME.pdf"
cp "$src\Ήρων\Ρεύμα\Οικιακά\Κίτρινα\HAPPY HOUR HOME.pdf" "$dst\iron\revma\oikiaka\kitrina\HAPPY HOUR HOME.pdf"
cp "$src\Ήρων\Ρεύμα\Οικιακά\Κίτρινα\YELLOW BENEFIT HOME.pdf" "$dst\iron\revma\oikiaka\kitrina\YELLOW BENEFIT HOME.pdf"
cp "$src\Ήρων\Ρεύμα\Οικιακά\Κίτρινα\YELLOW FREE HOME.pdf" "$dst\iron\revma\oikiaka\kitrina\YELLOW FREE HOME.pdf"
cp "$src\Ήρων\Ρεύμα\Οικιακά\Κίτρινα\YELLOW FREE STUDENT.pdf" "$dst\iron\revma\oikiaka\kitrina\YELLOW FREE STUDENT.pdf"
cp "$src\Ήρων\Ρεύμα\Οικιακά\Κίτρινα\YELLOW ONE HOME 2.pdf" "$dst\iron\revma\oikiaka\kitrina\YELLOW ONE HOME 2.pdf"
cp "$src\Ήρων\Ρεύμα\Οικιακά\Μπλε\BLUE GENEROUS HOME 6.pdf" "$dst\iron\revma\oikiaka\mple\BLUE GENEROUS HOME 6.pdf"
cp "$src\Ήρων\Ρεύμα\Οικιακά\Μπλε\BLUE GENEROUS HOME 7.pdf" "$dst\iron\revma\oikiaka\mple\BLUE GENEROUS HOME 7.pdf"
cp "$src\Ήρων\Ρεύμα\Οικιακά\Μπλε\BLUE GENEROUS MAX HOME 2.pdf" "$dst\iron\revma\oikiaka\mple\BLUE GENEROUS MAX HOME 2.pdf"
cp "$src\Ήρων\Ρεύμα\Οικιακά\Μπλε\BLUE GENEROUS MAX HOME 3.pdf" "$dst\iron\revma\oikiaka\mple\BLUE GENEROUS MAX HOME 3.pdf"
cp "$src\Ήρων\Ρεύμα\Οικιακά\Πράσινα\BASIC HOME.pdf" "$dst\iron\revma\oikiaka\prasina\BASIC HOME.pdf"
cp "$src\Ήρων\Ρεύμα\Επαγγελματικά\Κίτρινα\BUSINESS BENEFIT 2.pdf" "$dst\iron\revma\epaggelmatika\kitrina\BUSINESS BENEFIT 2.pdf"
cp "$src\Ήρων\Ρεύμα\Επαγγελματικά\Κίτρινα\HAPPY HOUR BUSINESS.pdf" "$dst\iron\revma\epaggelmatika\kitrina\HAPPY HOUR BUSINESS.pdf"
cp "$src\Ήρων\Ρεύμα\Επαγγελματικά\Κίτρινα\HAPPY HOUR FOR ALL BUSINESS.pdf" "$dst\iron\revma\epaggelmatika\kitrina\HAPPY HOUR FOR ALL BUSINESS.pdf"
cp "$src\Ήρων\Ρεύμα\Επαγγελματικά\Κίτρινα\YELLOW BENEFIT BUSINESS S.pdf" "$dst\iron\revma\epaggelmatika\kitrina\YELLOW BENEFIT BUSINESS S.pdf"
cp "$src\Ήρων\Ρεύμα\Επαγγελματικά\Κίτρινα\YELLOW FREE BUSINESS.pdf" "$dst\iron\revma\epaggelmatika\kitrina\YELLOW FREE BUSINESS.pdf"
cp "$src\Ήρων\Ρεύμα\Επαγγελματικά\Κίτρινα\YELLOW ONE BUSINESS S 2.pdf" "$dst\iron\revma\epaggelmatika\kitrina\YELLOW ONE BUSINESS S 2.pdf"
cp "$src\Ήρων\Ρεύμα\Επαγγελματικά\Κίτρινα\YELLOW PLUS BUSINESS L.pdf" "$dst\iron\revma\epaggelmatika\kitrina\YELLOW PLUS BUSINESS L.pdf"
cp "$src\Ήρων\Ρεύμα\Επαγγελματικά\Κίτρινα\YELLOW PLUS BUSINESS S.pdf" "$dst\iron\revma\epaggelmatika\kitrina\YELLOW PLUS BUSINESS S.pdf"
cp "$src\Ήρων\Ρεύμα\Επαγγελματικά\Κίτρινα\YELLOW PLUS HOME.pdf" "$dst\iron\revma\epaggelmatika\kitrina\YELLOW PLUS HOME.pdf"
cp "$src\Ήρων\Ρεύμα\Επαγγελματικά\Μπλε\BLUE GENEROUS BUSINESS 6.pdf" "$dst\iron\revma\epaggelmatika\mple\BLUE GENEROUS BUSINESS 6.pdf"
cp "$src\Ήρων\Ρεύμα\Επαγγελματικά\Μπλε\BLUE GENEROUS BUSINESS 7.pdf" "$dst\iron\revma\epaggelmatika\mple\BLUE GENEROUS BUSINESS 7.pdf"
cp "$src\Ήρων\Ρεύμα\Επαγγελματικά\Μπλε\BLUE GENEROUS MAX BUSINESS 2.pdf" "$dst\iron\revma\epaggelmatika\mple\BLUE GENEROUS MAX BUSINESS 2.pdf"
cp "$src\Ήρων\Ρεύμα\Επαγγελματικά\Μπλε\BLUE GENEROUS MAX BUSINESS 3.pdf" "$dst\iron\revma\epaggelmatika\mple\BLUE GENEROUS MAX BUSINESS 3.pdf"
cp "$src\Ήρων\Ρεύμα\Επαγγελματικά\Πορτοκαλί\HAPPY HOUR BUSINESS L.pdf" "$dst\iron\revma\epaggelmatika\portokali\HAPPY HOUR BUSINESS L.pdf"
cp "$src\Ήρων\Ρεύμα\Επαγγελματικά\Πράσινα\BASIC BUSINESS L.pdf" "$dst\iron\revma\epaggelmatika\prasina\BASIC BUSINESS L.pdf"
cp "$src\Ήρων\Ρεύμα\Επαγγελματικά\Πράσινα\BASIC BUSINESS S.pdf" "$dst\iron\revma\epaggelmatika\prasina\BASIC BUSINESS S.pdf"

# ===== VOLTON =====
cp "$src\Volton\Αέριο\Αίτηση Φ.Α..pdf" "$dst\volton\aerio\Aitisi FA.pdf"
cp "$src\Volton\Αέριο\Αίτηση Φ.Α. Επεξεργάσιμη.pdf" "$dst\volton\aerio\Aitisi FA Epexergasimh.pdf"
cp "$src\Volton\Αέριο\ΓΟ Φ.Α. ΧΠ.pdf" "$dst\volton\aerio\GO FA XP.pdf"
cp "$src\Volton\Αέριο\ΓΟ Φ.Α. ΧΠ Επεξεργάσιμη.pdf" "$dst\volton\aerio\GO FA XP Epexergasimh.pdf"
cp "$src\Volton\Ρεύμα\Οικιακό\Αίτηση Η.Ε..pdf" "$dst\volton\revma\oikiako\Aitisi HE.pdf"
cp "$src\Volton\Ρεύμα\Οικιακό\Αίτηση Η.Ε. Επεξεργάσιμη.pdf" "$dst\volton\revma\oikiako\Aitisi HE Epexergasimh.pdf"
cp "$src\Volton\Ρεύμα\Οικιακό\Γενικοί όροι Η.Ε. ΧΤ.pdf" "$dst\volton\revma\oikiako\Genikoi oroi HE XT.pdf"
cp "$src\Volton\Ρεύμα\Οικιακό\Γενικοί όροι Η.Ε. ΧΤ Επεξεργάσιμη.pdf" "$dst\volton\revma\oikiako\Genikoi oroi HE XT Epexergasimh.pdf"
cp "$src\Volton\Ρεύμα\Οικιακό\Κίτρινο\Γ1 Yellow Flat.pdf" "$dst\volton\revma\oikiako\kitrino\G1 Yellow Flat.pdf"
cp "$src\Volton\Ρεύμα\Οικιακό\Μπλε\Blue Flat Γ1.pdf" "$dst\volton\revma\oikiako\mple\Blue Flat G1.pdf"
cp "$src\Volton\Ρεύμα\Οικιακό\Μπλε\PROMO 6M.pdf" "$dst\volton\revma\oikiako\mple\PROMO 6M.pdf"
cp "$src\Volton\Ρεύμα\Οικιακό\Μπλε\PROMO 6M Παράταση.pdf" "$dst\volton\revma\oikiako\mple\PROMO 6M Paratash.pdf"
cp "$src\Volton\Ρεύμα\Οικιακό\Μπλε\Γ1 Blue Flat.pdf" "$dst\volton\revma\oikiako\mple\G1 Blue Flat.pdf"
cp "$src\Volton\Ρεύμα\Επαγγελματικό\Αίτηση Η.Ε..pdf" "$dst\volton\revma\epaggelmatiko\Aitisi HE.pdf"
cp "$src\Volton\Ρεύμα\Επαγγελματικό\Αίτηση Η.Ε. Επεξεργάσιμη.pdf" "$dst\volton\revma\epaggelmatiko\Aitisi HE Epexergasimh.pdf"
cp "$src\Volton\Ρεύμα\Επαγγελματικό\Γενικοί όροι Η.Ε. ΧΤ.pdf" "$dst\volton\revma\epaggelmatiko\Genikoi oroi HE XT.pdf"
cp "$src\Volton\Ρεύμα\Επαγγελματικό\Γενικοί όροι Η.Ε. ΧΤ Επεξεργάσιμη.pdf" "$dst\volton\revma\epaggelmatiko\Genikoi oroi HE XT Epexergasimh.pdf"
cp "$src\Volton\Ρεύμα\Επαγγελματικό\Κίτρινο\Γ21 Yellow Flat.pdf" "$dst\volton\revma\epaggelmatiko\kitrino\G21 Yellow Flat.pdf"
cp "$src\Volton\Ρεύμα\Επαγγελματικό\Μπλε\Blue Flat Γ21.pdf" "$dst\volton\revma\epaggelmatiko\mple\Blue Flat G21.pdf"
cp "$src\Volton\Ρεύμα\Επαγγελματικό\Μπλε\Γ21 Blue Flat.pdf" "$dst\volton\revma\epaggelmatiko\mple\G21 Blue Flat.pdf"
cp "$src\Volton\Ρεύμα\Επαγγελματικό\Μπλε\PROMO 6M.pdf" "$dst\volton\revma\epaggelmatiko\mple\PROMO 6M.pdf"
cp "$src\Volton\Ρεύμα\Επαγγελματικό\Μπλε\PROMO 6M Παράταση.pdf" "$dst\volton\revma\epaggelmatiko\mple\PROMO 6M Paratash.pdf"

# ===== PROTERGIA =====
cp "$src\Protergia\Αέριο\Οικιακό\Αίτηση Οικιακό Φ.Α..pdf" "$dst\protergia\aerio\oikiako\Aitisi Oikiako FA.pdf"
cp "$src\Protergia\Αέριο\Οικιακό\ΓΟΣ\ΓΟΣ Οικιακό Φ.Α..pdf" "$dst\protergia\aerio\oikiako\GOS Oikiako FA.pdf"
cp "$src\Protergia\Αέριο\Οικιακό\Απαιτούμενα Δικαιολογητικά\Απαιτούμενα Δικαιολογητικά.pdf" "$dst\protergia\aerio\oikiako\Apaitoumena Dikaiologitika.pdf"
cp "$src\Protergia\Αέριο\Επαγγελματικό\Αίτηση  Επαγγελματικό Φ.Α..pdf" "$dst\protergia\aerio\epaggelmatiko\Aitisi Epaggelmatiko FA.pdf"
cp "$src\Protergia\Αέριο\Επαγγελματικό\ΓΟΣ\ΓΟΣ Επαγγελματικό Φ.Α..pdf" "$dst\protergia\aerio\epaggelmatiko\GOS Epaggelmatiko FA.pdf"
cp "$src\Protergia\Αέριο\Επαγγελματικό\Απαιτούμενα Δικαιολογητικά\Απαιτούμενα Δικαιολογητικά.pdf" "$dst\protergia\aerio\epaggelmatiko\Apaitoumena Dikaiologitika.pdf"
cp "$src\Protergia\Ρεύμα\Οικιακό\Κίτρινο\Value Flex.pdf" "$dst\protergia\revma\oikiako\kitrino\Value Flex.pdf"
cp "$src\Protergia\Ρεύμα\Οικιακό\Κίτρινο\Value Lite.pdf" "$dst\protergia\revma\oikiako\kitrino\Value Lite.pdf"
cp "$src\Protergia\Ρεύμα\Οικιακό\Κίτρινο\Value Standard.pdf" "$dst\protergia\revma\oikiako\kitrino\Value Standard.pdf"
cp "$src\Protergia\Ρεύμα\Επαγγελματικό\eο1250-2_181_v2_012026_aitisi_epaggelmatiko_ε1_value_standard (1).pdf" "$dst\protergia\revma\epaggelmatiko\Aitisi Epaggelmatikoy e1.pdf"
cp "$src\Protergia\Ρεύμα\Επαγγελματικό\Κίτρινα\Επαγγελματικό 1 Value Simple.pdf" "$dst\protergia\revma\epaggelmatiko\kitrina\Epaggelmatiko 1 Value Simple.pdf"
cp "$src\Protergia\Ρεύμα\Επαγγελματικό\Κίτρινα\Επαγγελματικό 1 Value Standard.pdf" "$dst\protergia\revma\epaggelmatiko\kitrina\Epaggelmatiko 1 Value Standard.pdf"
cp "$src\Protergia\Ρεύμα\Επαγγελματικό\Κίτρινα\Επαγγελματικό 2 Value Simple.pdf" "$dst\protergia\revma\epaggelmatiko\kitrina\Epaggelmatiko 2 Value Simple.pdf"
cp "$src\Protergia\Ρεύμα\Επαγγελματικό\Κίτρινα\Επαγγελματικό 2 Value Standard.pdf" "$dst\protergia\revma\epaggelmatiko\kitrina\Epaggelmatiko 2 Value Standard.pdf"
cp "$src\Protergia\Ρεύμα\Επαγγελματικό\Κίτρινα\Επαγγελματικό 3 Value Simple.pdf" "$dst\protergia\revma\epaggelmatiko\kitrina\Epaggelmatiko 3 Value Simple.pdf"
cp "$src\Protergia\Ρεύμα\Επαγγελματικό\Κίτρινα\Επαγγελματικό 3 Value Standard.pdf" "$dst\protergia\revma\epaggelmatiko\kitrina\Epaggelmatiko 3 Value Standard.pdf"
cp "$src\Protergia\Ρεύμα\Επαγγελματικό\Μπλε\Επαγγελματικό 1 Value Sure.pdf" "$dst\protergia\revma\epaggelmatiko\mple\Epaggelmatiko 1 Value Sure.pdf"
cp "$src\Protergia\Ρεύμα\Επαγγελματικό\Μπλε\Επαγγελματικό 2 Value Sure.pdf" "$dst\protergia\revma\epaggelmatiko\mple\Epaggelmatiko 2 Value Sure.pdf"
cp "$src\Protergia\Ρεύμα\Επαγγελματικό\Μπλε\Επαγγελματικό 3 Value Sure.pdf" "$dst\protergia\revma\epaggelmatiko\mple\Epaggelmatiko 3 Value Sure.pdf"
cp "$src\Protergia\Ρεύμα\Επαγγελματικό\Πορτοκαλί\Επαγγελματικό 2 Dynamic One.pdf" "$dst\protergia\revma\epaggelmatiko\portokali\Epaggelmatiko 2 Dynamic One.pdf"
cp "$src\Protergia\Ρεύμα\Επαγγελματικό\Πράσινο\Επαγγελματικό 1 Value Special.pdf" "$dst\protergia\revma\epaggelmatiko\prasino\Epaggelmatiko 1 Value Special.pdf"
cp "$src\Protergia\Ρεύμα\Επαγγελματικό\Πράσινο\Επαγγελματικό 2 Value Special.pdf" "$dst\protergia\revma\epaggelmatiko\prasino\Epaggelmatiko 2 Value Special.pdf"

# ===== ENERWAVE =====
cp "$src\Enerwave\Ρεύμα\Οικιακό\Κίτρινο\Reward Night Saver.pdf" "$dst\enerwave\revma\oikiako\kitrino\Reward Night Saver.pdf"
cp "$src\Enerwave\Ρεύμα\Οικιακό\Κίτρινο\Reward Saver.pdf" "$dst\enerwave\revma\oikiako\kitrino\Reward Saver.pdf"
cp "$src\Enerwave\Ρεύμα\Οικιακό\Κίτρινο\Smart Zero.pdf" "$dst\enerwave\revma\oikiako\kitrino\Smart Zero.pdf"
cp "$src\Enerwave\Ρεύμα\Οικιακό\Κίτρινο\Smart.pdf" "$dst\enerwave\revma\oikiako\kitrino\Smart.pdf"
cp "$src\Enerwave\Ρεύμα\Επαγγελματικό\Κίτρινο\Reward Saver For Business.pdf" "$dst\enerwave\revma\epaggelmatiko\kitrino\Reward Saver For Business.pdf"
cp "$src\Enerwave\Ρεύμα\Επαγγελματικό\Κίτρινο\Smart Zero For Business.pdf" "$dst\enerwave\revma\epaggelmatiko\kitrino\Smart Zero For Business.pdf"
cp "$src\Enerwave\Ρεύμα\Επαγγελματικό\Μπλε\Bright Power Γ21.pdf" "$dst\enerwave\revma\epaggelmatiko\mple\Bright Power G21.pdf"
cp "$src\Enerwave\Ρεύμα\Επαγγελματικό\Μπλε\Bright Power Γ22-Γ23.pdf" "$dst\enerwave\revma\epaggelmatiko\mple\Bright Power G22-G23.pdf"
cp "$src\Enerwave\Ρεύμα\Επαγγελματικό\Μπλε\My Wave Daily 1 For Business.pdf" "$dst\enerwave\revma\epaggelmatiko\mple\My Wave Daily 1 For Business.pdf"
cp "$src\Enerwave\Ρεύμα\Επαγγελματικό\Μπλε\My Wave Daily 1.5 For Business.pdf" "$dst\enerwave\revma\epaggelmatiko\mple\My Wave Daily 1.5 For Business.pdf"
cp "$src\Enerwave\Ρεύμα\Επαγγελματικό\Μπλε\My Wave Daily 2 For Business.pdf" "$dst\enerwave\revma\epaggelmatiko\mple\My Wave Daily 2 For Business.pdf"
cp "$src\Enerwave\Ρεύμα\Επαγγελματικό\Μπλε\My Wave Daily 2.5 For Business.pdf" "$dst\enerwave\revma\epaggelmatiko\mple\My Wave Daily 2.5 For Business.pdf"
cp "$src\Enerwave\Ρεύμα\Επαγγελματικό\Μπλε\My Wave Daily 3 For Business.pdf" "$dst\enerwave\revma\epaggelmatiko\mple\My Wave Daily 3 For Business.pdf"
cp "$src\Enerwave\Ρεύμα\Επαγγελματικό\Μπλε\My Wave Daily Promo Δώρο το πάγιο 60ημ.pdf" "$dst\enerwave\revma\epaggelmatiko\mple\My Wave Daily Promo.pdf"
cp "$src\Enerwave\Ρεύμα\Επαγγελματικό\Μπλε\Reward Fee Free Γ21.pdf" "$dst\enerwave\revma\epaggelmatiko\mple\Reward Fee Free G21.pdf"
cp "$src\Enerwave\Ρεύμα\Επαγγελματικό\Μπλε\Reward Prime Γ21.pdf" "$dst\enerwave\revma\epaggelmatiko\mple\Reward Prime G21.pdf"
cp "$src\Enerwave\Ρεύμα\Επαγγελματικό\Πορτοκαλί\Smart Dynamic.pdf" "$dst\enerwave\revma\epaggelmatiko\portokali\Smart Dynamic.pdf"
cp "$src\Enerwave\Ρεύμα\Επαγγελματικό\Πράσινο\Ειδικό Τιμολόγιο Γ21.pdf" "$dst\enerwave\revma\epaggelmatiko\prasino\Eidiko Timologio G21.pdf"
cp "$src\Enerwave\Ρεύμα\Επαγγελματικό\Πράσινο\Ειδικό Τιμολόγιο Γ22-Γ23.pdf" "$dst\enerwave\revma\epaggelmatiko\prasino\Eidiko Timologio G22-G23.pdf"
cp "$src\Enerwave\Αέριο\Οικιακό\Σταθερό\Gas Home Bright New.pdf" "$dst\enerwave\aerio\oikiako\stathero\Gas Home Bright New.pdf"
cp "$src\Enerwave\Αέριο\Οικιακό\Σταθερό\Gas Home Bright Plus.pdf" "$dst\enerwave\aerio\oikiako\stathero\Gas Home Bright Plus.pdf"
cp "$src\Enerwave\Αέριο\Οικιακό\Σταθερό\Gas Home Bright Promo 50€.pdf" "$dst\enerwave\aerio\oikiako\stathero\Gas Home Bright Promo 50.pdf"
cp "$src\Enerwave\Αέριο\Οικιακό\Σταθερό\Gas Home Reward.pdf" "$dst\enerwave\aerio\oikiako\stathero\Gas Home Reward.pdf"
cp "$src\Enerwave\Αέριο\Οικιακό\Σταθερό\Gas Home Win.pdf" "$dst\enerwave\aerio\oikiako\stathero\Gas Home Win.pdf"
cp "$src\Enerwave\Αέριο\Οικιακό\Κυμαινόμενο\Gas Start κεντρική.pdf" "$dst\enerwave\aerio\oikiako\kymainom\Gas Start kentriki.pdf"
cp "$src\Enerwave\Αέριο\Οικιακό\Κυμαινόμενο\Gas start αυτόνομη.pdf" "$dst\enerwave\aerio\oikiako\kymainom\Gas Start autonomi.pdf"
cp "$src\Enerwave\Αέριο\Οικιακό\Κυμαινόμενο\Promo 200€ Gas Start 13-14 Μήνα.pdf" "$dst\enerwave\aerio\oikiako\kymainom\Promo 200 Gas Start 13-14 Mina.pdf"
cp "$src\Enerwave\Αέριο\Οικιακό\Κυμαινόμενο\Promo 200€ Gas Start.pdf" "$dst\enerwave\aerio\oikiako\kymainom\Promo 200 Gas Start.pdf"
cp "$src\Enerwave\Αέριο\Οικιακό\Κυμαινόμενο\Κοινόχρηστο\Gas Building Win.pdf" "$dst\enerwave\aerio\oikiako\koinoxristo\Gas Building Win.pdf"
cp "$src\Enerwave\Αέριο\Επαγγελματικό\Σταθερό\Gas Business Bright 12M.pdf" "$dst\enerwave\aerio\epaggelmatiko\stathero\Gas Business Bright 12M.pdf"
cp "$src\Enerwave\Αέριο\Επαγγελματικό\Κυμαινόμενο\Gas Business Win.pdf" "$dst\enerwave\aerio\epaggelmatiko\kymainom\Gas Business Win.pdf"
cp "$src\Enerwave\Αέριο\Οικιακό\Σταθερό\Κοινόχρηστο\Gas Building Bright 12M.pdf" "$dst\enerwave\aerio\epaggelmatiko\koinoxristo\Gas Building Bright 12M.pdf"

# ===== ΔΕΗ =====
cp "$src\ΔΕΗ\Αέριο\Σύμβαση_Φυσικού_Αερίου_ΤΗΛΕΜΑΤΙΚΗ.pdf" "$dst\dei\aerio\Symbasi Fysikou Aeriou TILEMATIKI.pdf"
cp "$src\ΔΕΗ\Αέριο\Οικιακό\Αίτηση Οικιακού - ΑΕΡΙΟ- MyHomeGasBenefit.pdf" "$dst\dei\aerio\oikiako\Aitisi Oikiakoy MyHomeGasBenefit.pdf"
cp "$src\ΔΕΗ\Αέριο\Οικιακό\Σταθερό\Αίτηση Οικιακού - ΑΕΡΙΟ- MyHomeGasControl.pdf" "$dst\dei\aerio\oikiako\stathero\Aitisi MyHomeGasControl.pdf"
cp "$src\ΔΕΗ\Αέριο\Κοινόχρηστο\Σταθερό\MyBuilding Gas Control.pdf" "$dst\dei\aerio\koinoxristo\stathero\MyBuilding Gas Control.pdf"
cp "$src\ΔΕΗ\Αέριο\Επαγγελματικό\Κυμμαινόμενο\MyBusiness Gas Benefit.pdf" "$dst\dei\aerio\epaggelmatiko\kymainom\MyBusiness Gas Benefit.pdf"
cp "$src\ΔΕΗ\Ρεύμα\Οικιακό\Αίτηση Οικιακού - ΡΕΥΜΑ - myHome4all - Green.pdf" "$dst\dei\revma\oikiako\Aitisi myHome4all Green.pdf"
cp "$src\ΔΕΗ\Ρεύμα\Οικιακό\Αίτηση Οικιακού - ΡΕΥΜΑ - myHome4all OneRate - Green.pdf" "$dst\dei\revma\oikiako\Aitisi myHome4all OneRate Green.pdf"
cp "$src\ΔΕΗ\Ρεύμα\Οικιακό\Αίτηση Οικιακού - ΡΕΥΜΑ - myHome4Students - Green.pdf" "$dst\dei\revma\oikiako\Aitisi myHome4Students Green.pdf"
cp "$src\ΔΕΗ\Ρεύμα\Οικιακό\Αίτηση Οικιακού - ΡΕΥΜΑ - myHomeEnter - Green.pdf" "$dst\dei\revma\oikiako\Aitisi myHomeEnter Green.pdf"
cp "$src\ΔΕΗ\Ρεύμα\Οικιακό\Αίτηση Οικιακού - ΡΕΥΜΑ - myHomeEnterTwo- Green.pdf" "$dst\dei\revma\oikiako\Aitisi myHomeEnterTwo Green.pdf"
cp "$src\ΔΕΗ\Ρεύμα\Οικιακό\Αίτηση Οικιακού - ΡΕΥΜΑ - myHomePlan - Green.pdf" "$dst\dei\revma\oikiako\Aitisi myHomePlan Green.pdf"
cp "$src\ΔΕΗ\Ρεύμα\Οικιακό\Αίτηση Οικιακού - ΡΕΥΜΑ - Γ1-Γ1Ν Οικιακό - Green.pdf" "$dst\dei\revma\oikiako\Aitisi G1-G1N Oikiako Green.pdf"
cp "$src\ΔΕΗ\Ρεύμα\Οικιακό\Ανανέωση - Αίτηση Οικιακού - ΡΕΥΜΑ - myHomeEnter - Green.pdf" "$dst\dei\revma\oikiako\Ananewsi myHomeEnter Green.pdf"
cp "$src\ΔΕΗ\Ρεύμα\Επαγγελματικό\Έως 25 kVA\Επαγ - έως 25ΚVA - Ελευθ - MyBusiness4all+.pdf" "$dst\dei\revma\epaggelmatiko\eos25kva\MyBusiness4all plus.pdf"
cp "$src\ΔΕΗ\Ρεύμα\Επαγγελματικό\Έως 25 kVA\Επαγ - έως 25ΚVA - Ελευθ - MyBusiness4all.pdf" "$dst\dei\revma\epaggelmatiko\eos25kva\MyBusiness4all.pdf"
cp "$src\ΔΕΗ\Ρεύμα\Επαγγελματικό\Έως 25 kVA\Επαγ - έως 25ΚVA - Ελευθ - MyBusinessEnter (1).pdf" "$dst\dei\revma\epaggelmatiko\eos25kva\MyBusinessEnter.pdf"
cp "$src\ΔΕΗ\Ρεύμα\Επαγγελματικό\Άνω των 25 kVA\Κίτρινο\Επαγ - από 25 KVA - Ελευθ - Mybusiness4all+.pdf" "$dst\dei\revma\epaggelmatiko\ano25kva\Mybusiness4all plus.pdf"
cp "$src\ΔΕΗ\Ρεύμα\Επαγγελματικό\Άνω των 25 kVA\Κίτρινο\Επαγ - από 25 KVA - Ελευθ - Mybusiness4all.pdf" "$dst\dei\revma\epaggelmatiko\ano25kva\Mybusiness4all.pdf"
cp "$src\ΔΕΗ\Ρεύμα\Επαγγελματικό\Άνω των 25 kVA\Κίτρινο\Επαγ - από 25 KVA - Ελευθ - Γ22.pdf" "$dst\dei\revma\epaggelmatiko\ano25kva\G22.pdf"

Write-Host "`n✅ All files copied successfully!"
